#!/bin/bash

dir_prefix="./build/images/"

if ! [ -d "$dir_prefix""covers" ]; then
    mkdir "$dir_prefix""covers" 
fi

if ! [ -d "$dir_prefix""bgs" ]; then
    mkdir "$dir_prefix""bgs" 
fi

for img in `seq 1 28`
do
    convert "$dir_prefix""raw/""$img"".jpg" -resize 170x170^ -gravity center -extent 170x170 "$dir_prefix""covers/""$img"".jpg"
    convert "$dir_prefix""raw/""$img"".jpg" -resize 200x200^ -blur 0x2 -modulate 100,20 "$dir_prefix""bgs/""$img"".jpg"
done
